prog:fonctions.o main.o 
	gcc fonctions.o main.o -o prog -g -lSDL -lSDL_mixer -lSDL_image -lSDL_ttf  
main.o:main.c 
	gcc -c main.c -g -lSDL -lSDL_mixer -lSDL_image -lSDL_ttf 
fonctions.o:fonctions.c 
	gcc -c fonctions.c -g -lSDL -lSDL_mixer -lSDL_image -lSDL_ttf 
