prog:ES.o main.o 
	gcc ES.o main.o -o prog -g -lSDL -lSDL_mixer -lSDL_image -lSDL_ttf  
main.o:main.c 
	gcc -c main.c -g -lSDL -lSDL_mixer -lSDL_image -lSDL_ttf 
ES.o:ES.c 
	gcc -c ES.c -g -lSDL -lSDL_mixer -lSDL_image -lSDL_ttf 
